version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 429121993112.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t task-21-apache .
      - docker tag task-21-apache:latest 429121993112.dkr.ecr.eu-central-1.amazonaws.com/task-21-apache:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 429121993112.dkr.ecr.eu-central-1.amazonaws.com/task-21-apache:latest