apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
# eksctl create cluster -f cluster.yaml — create cluster
# eksctl delete cluster -f cluster.yaml — delete cluster
metadata:
  name: basic-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 10