apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpa-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      allow: true