apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    volumeSize: 10
    ssh:
      allow: true
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 3
    volumeSize: 10
    ssh:
      allow: true