#! /usr/bin/env python3
import smtplib
mail_from = 'alexandrovichvadim@gmail.com'
smtp_password = 'dpcn****xdlk****'
mail_to = 'v.alexandrovich93@gmail.com'
server = 'smtp.gmail.com'
port = 587
msg = "Any new commit"

s = smtplib.SMTP(server, port)
s.ehlo()
s.starttls()
s.login(mail_from, smtp_password)
s.sendmail(mail_from, mail_to , msg)
s.quit()