---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    labels:
      app: {{ .Release.Name }}-nginx
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: 80
          name: {{ .Release.Name }}-nginx
        resources:
            limits:
              memory: 256Mi
              cpu: "0.3"
            requests:
              memory: 256Mi
              cpu: "0.3"
