apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - nginx.aleksandrovich.ml
      - argocd.aleksandrovich.ml
      secretName: letsencrypt
  rules:
    - host: nginx.aleksandrovich.ml
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-nginx
              port:
                number: 80
    - host: argocd.aleksandrovich.ml
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              app.kubernetes.io/name: argocd-server
              port:
                number: 80

